"""Add is_admin flag to User model

Revision ID: 0b6c3f673e2d
Revises: 9a7ee58f218d
Create Date: 2025-04-09 13:14:24.846070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6c3f673e2d'
down_revision = '9a7ee58f218d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Provide server_default='0' for SQLite compatibility when adding NOT NULL boolean
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
    # ### end Alembic commands ###
